var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "d Z yyyy",
            "fulldayvalue": "d/M/yyyy",
            "Md": "W M/d",
            "Md3": "d Z",
            "separator": "/",
            "year_index": 2,
            "month_index":1,
            "day_index": 0,
            "day": "j",
            "sun": "Dim",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Jui",
            "jul": "Jul",
            "aug": "Auo",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Par encore implémenté",
        "to_date_view": "Voir journée",
        "i_undefined": "Indéfini",
        "allday_event": "Journée entière",
        "repeat_event": "Evènement récurrent",
        "time": "Heure",
        "event": "Evènement",
        "location": "Lieu",
        "participant": "Participant",
        "get_data_exception": "Erreur récup. données",
        "new_event": "Nouvel evnt",
        "confirm_delete_event": "Supprimer cet évènement ?",
        "confrim_delete_event_or_all": "Supprimer tous les évènements ou seulement celui-là ?\r\n[OK] pour supprimer celui-là, [Cancel] pour les supprimer tous",
        "data_format_error": "Erreur de format de données",
        "invalid_title": "Le titre de l'évènement ne peut être vide ni contenir ($<>)",
        "view_no_ready": "Vue pas encore prête",
        "example": "par ex. : réunion à 12h12",
        "content": "Quoi",
        "create_event": "Créer évènement",
        "update_detail": "Editer détails",
        "click_to_detail": "Voir détails",
        "i_delete": "Supprimer",
        "day_plural": "jours",
        "others": "Autres",
        "item": ""
    }
});
