var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "yyyy年 Z d日",
            "fulldayvalue": "M/d/yyyy",
            "Md": "M月d日(W)",
            "Md3": "Z d日",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "日",
            "mon": "月",
            "tue": "火",
            "wed": "水",
            "thu": "木",
            "fri": "金",
            "sat": "土",
            "jan": "1月",
            "feb": "2月",
            "mar": "3月",
            "apr": "4月",
            "may": "5月",
            "jun": "6月",
            "jul": "7月",
            "aug": "8月",
            "sep": "9月",
            "oct": "10月",
            "nov": "11月",
            "dec": "12月"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "終日",
        "repeat_event": "繰り返し",
        "time": "日時",
        "event": "予定",
        "location": "場所",
        "participant": "関係者",
        "get_data_exception": "Exception when getting data",
        "new_event": "新規に予定を作成",
        "confirm_delete_event": "この予定を削除?",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "予定タイトルが未入力・形式エラー",
        "view_no_ready": "View is not ready",
        "example": "例) 障害報告 107会議室",
        "content": "予定タイトル",
        "create_event": "予定を作成",
        "update_detail": "予定の詳細を編集",
        "click_to_detail": "予定を見る",
        "i_delete": "削除",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
